// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoErr.Data;

#nullable disable

namespace ProjetoErr.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjetoErr.Models.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarca"), 1L, 1);

                    b.Property<string>("dsMarca")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMarca");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            IdMarca = 1,
                            dsMarca = "Renault"
                        },
                        new
                        {
                            IdMarca = 2,
                            dsMarca = "Fiat"
                        },
                        new
                        {
                            IdMarca = 3,
                            dsMarca = "Honda"
                        });
                });

            modelBuilder.Entity("ProjetoErr.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = "",
                            Longitude = "",
                            PasswordHash = new byte[] { 130, 38, 68, 20, 231, 112, 88, 154, 88, 63, 188, 186, 147, 119, 113, 104, 233, 51, 121, 153, 92, 228, 79, 242, 253, 143, 94, 77, 183, 229, 236, 167, 5, 113, 255, 28, 30, 135, 33, 8, 18, 65, 161, 55, 238, 132, 15, 177, 92, 11, 190, 98, 95, 122, 87, 192, 112, 118, 160, 8, 24, 191, 69, 34 },
                            PasswordSalt = new byte[] { 222, 220, 114, 248, 85, 33, 182, 134, 32, 127, 76, 78, 131, 5, 159, 244, 17, 110, 187, 59, 240, 124, 50, 190, 213, 176, 49, 52, 68, 5, 144, 206, 105, 32, 33, 105, 62, 163, 19, 200, 159, 68, 141, 79, 45, 199, 189, 44, 86, 243, 8, 132, 169, 138, 176, 140, 149, 204, 37, 51, 31, 88, 122, 0, 220, 209, 17, 90, 219, 125, 249, 38, 11, 141, 44, 55, 41, 106, 10, 172, 29, 232, 137, 6, 97, 188, 4, 250, 165, 117, 191, 238, 109, 74, 240, 83, 11, 27, 29, 90, 103, 232, 108, 15, 32, 4, 46, 92, 235, 175, 9, 65, 147, 250, 231, 238, 166, 252, 142, 73, 2, 21, 97, 100, 245, 93, 178, 18 },
                            Username = "UsuarioAdmin"
                        });
                });

            modelBuilder.Entity("ProjetoErr.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClasseEnum")
                        .HasColumnType("int");

                    b.Property<string>("IdMarca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
